### ISSUE TITLE
UVM-SystemC and SCV appearance

### ISSUE THREAD

**Issue by basarts** [barnasc/systemc.org#1]
W.r.t. the picture: we could add UVM-SystemC on top of TLM. Next to that, I'd make the SCV box dotted as this is a legacy library and not maintained/updated anymore.

W.r.t. to the text and top right link box: also there I'd emphasize UVM-SystemC rather than SCV, as UVM-SystemC now is only mentioned at the bottom of the page. E.g. we could replace the header/link with "SystemC Verification (UVM-SystemC)" and swap the SCV and UVM-SystemC descriptions at the bottom.

**Comment by barnasc** [comment]
The picture is a few years old and needs an update. I will search for the source file of the graphics so we can make these updates. We might need to check with the corresponding SystemC WG if they agree with the proposed update.

The ToC box is automatically generated based on the section header. We can update section and its header. Pull request of the Markdown file is appreciated ;-)

**Comment by barnasc** [comment]
Updated picture in https://github.com/barnasc/systemc.org/commit/977c315eab06933832fda47937bf475a2881e126
